-- MySQL Script generated by MySQL Workbench
-- Mon Nov 16 12:33:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mask_detection_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mask_detection_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mask_detection_database` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mask_detection_database` ;

-- -----------------------------------------------------
-- Table `mask_detection_database`.`http_req`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mask_detection_database`.`http_req` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `instanceID` VARCHAR(100) NOT NULL,
  `timestamp` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10162
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mask_detection_database`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mask_detection_database`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `admin` BINARY(2) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mask_detection_database`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mask_detection_database`.`photo` (
  `photo_id` VARCHAR(200) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`photo_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `photo_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mask_detection_database`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
